bundle:
  deploy:
    zarf-packages:
      dubbd-k3d:
        set:
          # -- Domain name for the K3D cluster
          domain: bigbang.dev
          # -- TLS key
          key_file: bigbang.dev.key
          # -- TLS cert
          cert_file: bigbang.dev.cert
          # -- k3d host path
          host_path: "/var/lib/rancher/k3s/storage/*"
      external-dns:
        set:
          name: k3d-k3s-default
          external_dns_values: k3d-deploy-external-dns-values.yaml
